name: Publish KanbanCord Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test_project:
    name: Build Project
    uses: j4asper/KanbanCord/.github/workflows/unit-tests.yml@main

  build_and_publish_bot_docker_image:
    name: Build and Publish Bot Docker Image
    runs-on: ubuntu-latest
    needs: test_project
    env:
      IMAGE_NAME_DOCKERHUB: ${{ secrets.DOCKER_USERNAME }}/kanbancord
      IMAGE_NAME_GHCR: ghcr.io/${{ github.repository_owner }}/kanbancord
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -f ./Dockerfile \
            --build-arg application_version=${{ github.ref_name }} \
            -t $IMAGE_NAME_DOCKERHUB:${{ github.ref_name }} \
            -t $IMAGE_NAME_DOCKERHUB:latest \
            -t $IMAGE_NAME_GHCR:${{ github.ref_name }} \
            -t $IMAGE_NAME_GHCR:latest \
            .

      - name: Push to Docker Hub
        run: |
          docker push $IMAGE_NAME_DOCKERHUB:${{ github.ref_name }}
          docker push $IMAGE_NAME_DOCKERHUB:latest

      - name: Push to GitHub Container Registry
        run: |
          docker push $IMAGE_NAME_GHCR:${{ github.ref_name }}
          docker push $IMAGE_NAME_GHCR:latest
